"""Update users

Revision ID: 11697753f488
Revises: 90ee3629420f
Create Date: 2025-11-13 17:55:39.836612

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '11697753f488'
down_revision: Union[str, Sequence[str], None] = '90ee3629420f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=False))
    op.add_column(
        'users', sa.Column('first_name', sa.String(length=50), nullable=False)
    )
    op.add_column(
        'users', sa.Column('middle_name', sa.String(length=50), nullable=True)
    )
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
