"""Create-analyze-table

Revision ID: 2a18839a71e1
Revises: 11697753f488
Create Date: 2025-11-17 10:13:21.608464

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a18839a71e1'
down_revision: Union[str, Sequence[str], None] = '11697753f488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portfolio_calculation_explanations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('portfolio_id', sa.Integer(), nullable=False),
        sa.Column('explanation_text', sa.Text(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['portfolio_id'],
            ['portfolios.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_portfolio_calculation_explanations_id'),
        'portfolio_calculation_explanations',
        ['id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_portfolio_calculation_explanations_id'),
        table_name='portfolio_calculation_explanations',
    )
    op.drop_table('portfolio_calculation_explanations')
    # ### end Alembic commands ###
