"""Create-portfolio-tables

Revision ID: 35c1eebee696
Revises: 6a60bd59bd5f
Create Date: 2025-11-13 14:59:23.751899

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '35c1eebee696'
down_revision: Union[str, Sequence[str], None] = '6a60bd59bd5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
