"""update asset table

Revision ID: 6a60bd59bd5f
Revises: 0550a85b327d
Create Date: 2025-10-30 15:38:59.810843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a60bd59bd5f'
down_revision: Union[str, Sequence[str], None] = '0550a85b327d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('ticker', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'ticker')
    # ### end Alembic commands ###
