"""Create-portfolio-tables

Revision ID: 90ee3629420f
Revises: 35c1eebee696
Create Date: 2025-11-13 17:03:28.191213

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90ee3629420f'
down_revision: Union[str, Sequence[str], None] = '35c1eebee696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=100), nullable=True),
        sa.Column(
            'is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True
        ),
        sa.Column(
            'created_at', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table(
        'portfolios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('portfolio_name', sa.String(length=100), nullable=False),
        sa.Column('target_amount', sa.Float(), nullable=False),
        sa.Column('initial_capital', sa.Float(), nullable=False),
        sa.Column('investment_term_months', sa.Integer(), nullable=False),
        sa.Column('annual_inflation_rate', sa.Float(), nullable=False),
        sa.Column('future_value_with_inflation', sa.Float(), nullable=False),
        sa.Column('risk_profile', sa.String(length=50), nullable=False),
        sa.Column('time_horizon', sa.String(length=20), nullable=False),
        sa.Column('smart_goal', sa.Text(), nullable=True),
        sa.Column('total_investment', sa.Float(), nullable=False),
        sa.Column('expected_portfolio_return', sa.Float(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_index(
        op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False
    )
    op.create_table(
        'monthly_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('portfolio_id', sa.Integer(), nullable=False),
        sa.Column('monthly_payment', sa.Float(), nullable=False),
        sa.Column('future_capital', sa.Float(), nullable=False),
        sa.Column('total_months', sa.Integer(), nullable=False),
        sa.Column('monthly_rate', sa.Float(), nullable=False),
        sa.Column('annuity_factor', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['portfolio_id'],
            ['portfolios.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('portfolio_id'),
    )
    op.create_index(
        op.f('ix_monthly_payments_id'), 'monthly_payments', ['id'], unique=False
    )
    op.create_table(
        'portfolio_compositions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('portfolio_id', sa.Integer(), nullable=False),
        sa.Column('asset_type', sa.String(length=50), nullable=False),
        sa.Column('target_weight', sa.Float(), nullable=False),
        sa.Column('actual_weight', sa.Float(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['portfolio_id'],
            ['portfolios.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_portfolio_compositions_id'),
        'portfolio_compositions',
        ['id'],
        unique=False,
    )
    op.create_table(
        'step_by_step_plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('portfolio_id', sa.Integer(), nullable=False),
        sa.Column('generated_at', sa.DateTime(), nullable=False),
        sa.Column('total_steps', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['portfolio_id'],
            ['portfolios.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('portfolio_id'),
    )
    op.create_index(
        op.f('ix_step_by_step_plans_id'), 'step_by_step_plans', ['id'], unique=False
    )
    op.create_table(
        'asset_allocations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('portfolio_composition_id', sa.Integer(), nullable=False),
        sa.Column('asset_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('target_weight', sa.Float(), nullable=False),
        sa.Column('purchase_price', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['asset_id'],
            ['assets.id'],
        ),
        sa.ForeignKeyConstraint(
            ['portfolio_composition_id'],
            ['portfolio_compositions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_asset_allocations_id'), 'asset_allocations', ['id'], unique=False
    )
    op.create_table(
        'plan_steps',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('step_by_step_plan_id', sa.Integer(), nullable=False),
        sa.Column('step_number', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['step_by_step_plan_id'],
            ['step_by_step_plans.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_plan_steps_id'), 'plan_steps', ['id'], unique=False)
    op.create_table(
        'step_actions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_step_id', sa.Integer(), nullable=False),
        sa.Column('action_text', sa.Text(), nullable=False),
        sa.Column('action_order', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['plan_step_id'],
            ['plan_steps.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_step_actions_id'), 'step_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_actions_id'), table_name='step_actions')
    op.drop_table('step_actions')
    op.drop_index(op.f('ix_plan_steps_id'), table_name='plan_steps')
    op.drop_table('plan_steps')
    op.drop_index(op.f('ix_asset_allocations_id'), table_name='asset_allocations')
    op.drop_table('asset_allocations')
    op.drop_index(op.f('ix_step_by_step_plans_id'), table_name='step_by_step_plans')
    op.drop_table('step_by_step_plans')
    op.drop_index(
        op.f('ix_portfolio_compositions_id'), table_name='portfolio_compositions'
    )
    op.drop_table('portfolio_compositions')
    op.drop_index(op.f('ix_monthly_payments_id'), table_name='monthly_payments')
    op.drop_table('monthly_payments')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
