"""init

Revision ID: d3b5597c7a7c
Revises: a11f1f187581
Create Date: 2025-09-28 19:35:31.603160

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d3b5597c7a7c"
down_revision: Union[str, Sequence[str], None] = "a11f1f187581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
