"""add new table

Revision ID: e0e2207c8aa0
Revises: ed2f99ac2e05
Create Date: 2025-10-27 23:09:35.337499

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'e0e2207c8aa0'
down_revision: Union[str, Sequence[str], None] = 'ed2f99ac2e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
