"""add new table

Revision ID: ed2f99ac2e05
Revises: 83bb61d1c8d7
Create Date: 2025-10-27 23:00:25.507685

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'ed2f99ac2e05'
down_revision: Union[str, Sequence[str], None] = '83bb61d1c8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
